In [1]:
import hdbscan
from sklearn.datasets import make_blobs

In [2]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('points.csv')

In [4]:
df=df.values

In [5]:
df

array([[-0.73956248, -0.68543016, -0.49772607, ...,  1.38999185,
         2.65036287, -0.13830415],
       [-0.73956248, -0.68543016, -0.49772607, ...,  1.38999185,
         2.65036287, -0.13830415],
       [-0.73956248, -0.68543016, -0.49772607, ...,  1.38999185,
         2.65036287, -0.13830415],
       ..., 
       [ 1.35215081, -2.00430166, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415],
       [ 1.35215081, -2.00430166, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415],
       [ 1.35215081, -1.67458378, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415]])

In [6]:
clusterer = hdbscan.HDBSCAN(min_cluster_size=30)

In [7]:
clusterer.fit(df)

HDBSCAN(algorithm='best', allow_single_cluster=False, alpha=1.0,
    approx_min_span_tree=True, cluster_selection_method='eom',
    core_dist_n_jobs=4, gen_min_span_tree=False, leaf_size=40,
    match_reference_implementation=False, memory=Memory(cachedir=None),
    metric='euclidean', min_cluster_size=30, min_samples=None, p=None,
    prediction_data=False)

In [8]:
clusterer.labels_

array([5, 5, 5, ..., 3, 3, 9])

In [9]:
clusterer.labels_.max()

16

In [10]:
clusterer.probabilities_

array([ 0.79944791,  0.79944791,  0.79944791, ...,  0.80498114,
        0.80498114,  0.68167919])