In [1]:
import hdbscan
from sklearn.metrics import silhouette_score

In [2]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('weather.csv',header=None)

In [4]:
df=df.values

In [5]:
df

array([[  1.,   5.,  25., ...,   1.,   1.,   0.],
       [  0.,   6.,  40., ...,   1.,   1.,   0.],
       [  0.,   6.,  40., ...,   1.,   1.,   0.],
       ..., 
       [  1.,   2.,  40., ...,   1.,   0.,   0.],
       [  1.,   2.,  40., ...,   1.,   0.,   0.],
       [  1.,   3.,  40., ...,   1.,   0.,   0.]])

In [6]:
df.shape

(5914, 10)

In [7]:
clusterer = hdbscan.HDBSCAN(min_cluster_size=20)

In [8]:
clusterer.fit(df)

HDBSCAN(algorithm='best', allow_single_cluster=False, alpha=1.0,
    approx_min_span_tree=True, cluster_selection_method='eom',
    core_dist_n_jobs=4, gen_min_span_tree=False, leaf_size=40,
    match_reference_implementation=False, memory=Memory(cachedir=None),
    metric='euclidean', min_cluster_size=20, min_samples=None, p=None,
    prediction_data=False)

In [9]:
clusterer.labels_

array([7, 7, 7, ..., 7, 7, 7])

In [10]:
clusterer.labels_.max()

30

In [11]:
clusterer.probabilities_

array([ 0.71206899,  0.97332853,  0.97332853, ...,  1.        ,
        1.        ,  1.        ])

In [12]:
influence = pd.read_csv('influence.csv',header=None)

In [13]:
influence=influence.values

In [14]:
influence

array([[  0.        ,   7.4       ,  30.        ,   1.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ],
       ..., 
       [  0.        ,   4.05      ,  32.        ,   1.        ],
       [  0.        ,   4.05      ,  32.        ,   1.        ],
       [  1.        ,   1.71666667,  32.        ,   2.        ]])

In [15]:
labels=clusterer.labels_
influence_cluster=np.c_[influence,labels]

In [16]:
influence_cluster

array([[  0.        ,   7.4       ,  30.        ,   1.        ,   7.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ,   7.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ,   7.        ],
       ..., 
       [  0.        ,   4.05      ,  32.        ,   1.        ,   7.        ],
       [  0.        ,   4.05      ,  32.        ,   1.        ,   7.        ],
       [  1.        ,   1.71666667,  32.        ,   2.        ,   7.        ]])

In [17]:
np.save("hdbscan_result",influence_cluster)

In [18]:
silhouette_score(df, labels)

0.22372500460815689