In [1]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
import numpy as np

In [3]:
scaler = StandardScaler()

In [4]:
df = pd.read_csv('forecast_influence.csv')

In [5]:
df=df.values

In [6]:
df=df[:,1:]

In [7]:
df=df[:,:-4]

In [8]:
df.shape

(5914, 10)

In [9]:
scaler.fit(df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
df=scaler.fit_transform(df)

In [11]:
df

array([[ 1.35215081, -1.01514804, -0.73704314, ...,  1.38999185,
         2.65036287, -0.13830415],
       [-0.73956248, -0.68543016, -0.49772607, ...,  1.38999185,
         2.65036287, -0.13830415],
       [-0.73956248, -0.68543016, -0.49772607, ...,  1.38999185,
         2.65036287, -0.13830415],
       ..., 
       [ 1.35215081, -2.00430166, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415],
       [ 1.35215081, -2.00430166, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415],
       [ 1.35215081, -1.67458378, -0.49772607, ...,  1.38999185,
        -0.37730683, -0.13830415]])

In [12]:
kmeans = KMeans(n_clusters=19, random_state=0).fit(df)

In [13]:
labels=kmeans.labels_
np.round_(labels)

array([ 5,  5,  5, ...,  6,  6, 14], dtype=int32)

In [14]:
labels

array([ 5,  5,  5, ...,  6,  6, 14], dtype=int32)

In [15]:
kmeans.cluster_centers_

array([[-0.73956248,  0.62089152,  0.77918365, -0.27719855, -0.53749297,
        -0.58790145, -0.75577831, -0.71942868, -0.37730683, -0.13830415],
       [ 1.2275381 , -1.4087049 , -0.90419168, -0.27719855, -0.51864257,
         1.51022129,  1.32313933,  1.32715805, -0.37730683, -0.13830415],
       [-0.73956248,  0.63344134,  0.39531651, -0.27719855,  1.92563393,
         0.84567361, -0.75577831, -0.71942868,  2.65036287, -0.13830415],
       [ 1.31728892, -0.82281261, -0.89339695,  0.43500029, -0.01938998,
         2.96267256,  1.32313933,  1.31967783, -0.2763845 ,  7.23044115],
       [-0.73956248,  0.61481321,  0.45075369, -0.27719855,  0.84423217,
        -0.97732045, -0.73228771, -0.71942868, -0.37730683, -0.13830415],
       [ 0.21504493,  0.07579768, -0.56464919, -0.2511266 ,  1.94344394,
         0.32543399,  1.32313933,  1.38999185,  2.65036287, -0.13830415],
       [ 1.35215081, -1.65397642, -0.745499  ,  3.60752242, -0.39544319,
         0.00783884,  1.31274474,  1.37944475

In [16]:
np.savetxt("label.csv", labels, delimiter=",")
np.savetxt("points.csv", df, delimiter=",")