In [1]:
from sklearn.cluster import KMeans

In [4]:
import numpy as np

In [5]:
X = np.array([[1, 2, 2], [1, 4, 3], [1, 0, 2],[4, 2, 3], [4, 4, 2], [4, 0, 3]])

In [6]:
X

array([[1, 2, 2],
       [1, 4, 3],
       [1, 0, 2],
       [4, 2, 3],
       [4, 4, 2],
       [4, 0, 3]])

In [15]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

In [16]:
kmeans.labels_

array([1, 0, 1, 2, 0, 2], dtype=int32)

In [17]:
kmeans.predict([[0, 0, 0 ], [4, 4, 4]])

array([1, 0], dtype=int32)

In [18]:
kmeans.cluster_centers_

array([[ 2.5,  4. ,  2.5],
       [ 1. ,  1. ,  2. ],
       [ 4. ,  1. ,  3. ]])