In [1]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
import numpy as np

In [3]:
scaler = StandardScaler()

In [4]:
df = pd.read_csv('forecast_influence.csv')

In [5]:
df=df.values

In [6]:
df=df[:,1:]

In [7]:
weather=df[:,:-4]
influence=df[:,-4:]

In [8]:
weather.shape

(5914, 10)

In [9]:
scaler.fit(weather)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [10]:
df=scaler.fit_transform(weather)

In [11]:
weather

array([[  1.,   5.,  25., ...,   1.,   1.,   0.],
       [  0.,   6.,  40., ...,   1.,   1.,   0.],
       [  0.,   6.,  40., ...,   1.,   1.,   0.],
       ..., 
       [  1.,   2.,  40., ...,   1.,   0.,   0.],
       [  1.,   2.,  40., ...,   1.,   0.,   0.],
       [  1.,   3.,  40., ...,   1.,   0.,   0.]])

In [12]:
kmeans = KMeans(n_clusters=19, random_state=0).fit(weather)

In [13]:
labels=kmeans.labels_
np.round_(labels)

array([13,  7,  7, ...,  3,  3,  3], dtype=int32)

In [14]:
labels

array([13,  7,  7, ...,  3,  3,  3], dtype=int32)

In [15]:
kmeans.cluster_centers_

array([[  1.00000000e+00,   6.79979466e+00,   1.48028747e+01,
          7.80287474e-02,   7.37782341e+00,   5.46817248e+00,
          6.16016427e-01,   5.87268994e-01,  -6.38378239e-16,
          5.55111512e-17],
       [  7.77156117e-16,   9.96330275e+00,   1.20000000e+02,
         -3.05311332e-16,   1.97724771e+01,   6.85321101e+00,
         -3.05311332e-15,  -4.60742555e-15,   5.32110092e-02,
         -2.08166817e-17],
       [  4.99600361e-16,   1.00000000e+01,   2.50000000e+02,
          8.32667268e-17,   2.16865672e+01,   7.10447761e+00,
          1.11022302e-16,   0.00000000e+00,   1.19402985e-01,
         -3.46944695e-18],
       [  1.22004357e-01,   7.82352941e+00,   3.85294118e+01,
          2.33115468e-01,   7.13071895e+00,   8.01089325e+00,
          5.51198257e-01,   5.35947712e-01,  -6.24500451e-16,
          2.17864924e-03],
       [  6.10622664e-16,   1.00000000e+01,   2.00000000e+02,
          7.86516854e-02,   1.13820225e+01,   9.49438202e+00,
          7.86516854e-02

In [16]:
np.savetxt("influence.csv", influence, delimiter=",")
np.savetxt("weather.csv", weather, delimiter=",")

In [17]:
influence_cluster=np.c_[influence,labels]

In [18]:
influence_cluster

array([[  0.        ,   7.4       ,  30.        ,   1.        ,  13.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ,   7.        ],
       [  0.        ,   7.4       ,  30.        ,   1.        ,   7.        ],
       ..., 
       [  0.        ,   4.05      ,  32.        ,   1.        ,   3.        ],
       [  0.        ,   4.05      ,  32.        ,   1.        ,   3.        ],
       [  1.        ,   1.71666667,  32.        ,   2.        ,   3.        ]])

In [19]:
np.save("kmean_result",influence_cluster)